### ISSUE TITLE
Speeds of (GPU 8x, 14x and yolov4dense) running on desktop GPU (RTX2080Ti) are same

### ISSUE THREAD

**Issue by pham-cong-nguyen** [nightsnack/YOLObile#7]
I run:
detect.py --weights 'weights/best14x-49.pt' -- img-size 512 --> runing time (11ms on RTX2080ti) 
detect.py --weights 'weights/best8x-514.pt -- img-size 512 --> runing time (11ms on RTX2080ti) 
detect.py --weights 'weights/yolov4dense.pt ' -- img-size 512 --> runing time (11ms on RTX2080ti) 

But when using check_compression.py, I see that FLOPS of these weights is still good

I just pip install -U -r requirements.txt, without docker build

So can you explain to me about this problem?

**Comment by nightsnack** [comment]
Yes sure. Our work targets on mobile devices and includes the pruning and compiler two parts. The repo on github is only about pruning. The pruned model needs the mobile compiler support to inference or acceleration. The mobile compiler is not open sourced right now.
For RTX 2080Ti, because Pytorch (running on desktop GPU) doesn't support sparse matrix, the inference speed of sparse models and dense models are the same.

**Comment by nightsnack** [comment]
This is a fairly common question. I pinned your issue.

**Comment by pham-cong-nguyen** [comment]
Thanks for your answer. So I will wait for Nvidia's update

**Comment by Wuqiman** [comment]
> The mobile compiler
Hi, may i ask you about that the mobile compiler is based on MNN? When the mobile compiler could  open source?Thank you very much~

**Comment by nightsnack** [comment]
Hi @Wuqiman , mobile compiler is not based on Alibaba MNN. Please refer to README.md. The compiler source code is associated with our collaborator at William & Mary, and has joint IP related stuff. We cannot open source this part now. Sorry for the inconvenience.
